title: Mauricio Padilla # your name (or website title) here
logo: "/images/Photo ID-Mauricio Padilla.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Hello! I am Mauricio Padilla. Specialized on journalism, communication, marketin and digital media production. Let’s get to know me better!<br>
  Second description 
  <br><br>
  <a href="www.linkedin.com/in/mauricio-padilla-">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

